jury/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    url(r"^accounts/", include("django.contrib.auth.urls")),
    path("", include("juryapp.urls")),
    path('admin/', admin.site.urls),
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
]

juryapp/urls.py
from django.urls import path
from .views import *
from django.conf.urls import include, url

app_name = "juryapp"

urlpatterns = [
    path("jury/<jury>/<panel_num>/", send_panel, name="send_panel"),
    path("jury/<jury>/", send_all, name="send_all"),
    path("", home, name="home"),
    path("add/<panel>/", add_number, name="add_juror"),
    path("dash/<panel>/<number>/", dash, name="dash"),
    path("delete/<jury>/", delete, name="delete"),
    path("delete/<member>/<jury>/", delete_number, name="delete_number"),
    path("settings", settings, name="settings"),
    url(r"^register/", register, name="register"),
]

juryapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django_random_id_model import RandomIDModel
from phonenumber_field.modelfields import PhoneNumberField
import datetime

class Number(models.Model):
    number = PhoneNumberField()
    def __str__(self):
         return str(self.number)

class Jury(RandomIDModel):
    judge = models.ForeignKey(User, on_delete=models.CASCADE)
    casename = models.CharField(max_length=100, default="")
    def __str__(self):
         return str(self.casename)

class Panel(RandomIDModel):
    jury = models.ForeignKey(Jury, on_delete=models.CASCADE)
    number = models.IntegerField()
    members = models.ManyToManyField(Number)
    def __str__(self):
         return str(self.number)

class Message(models.Model):
    judge = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=100, default="Message")
    panel = models.ManyToManyField(Panel)
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
         return str(self.message)

juryapp/forms.py
from django import forms
from .models import *
from phonenumber_field.formfields import PhoneNumberField

class MessageForm(forms.ModelForm):
    message_form = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    message = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Message to jurors...",
                "class": "border-0 p-3 h-100 w-100",
            }
        ),
        label="",)

    class Meta:
        model = Message
        exclude = ("judge", "panel",)

class JuryCreate(forms.Form):
    jury_form = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    panel_num = forms.IntegerField(required=True,
    widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Number of panels",
                "class": "form-control w-100",
            }
        ),
        label="",)
    casename = forms.CharField(required=True,
    widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Casename",
                "class": "form-control w-100",
            }
        ),
        label="",)

class AddJuror(forms.ModelForm):
    number = PhoneNumberField(region="US")

    class Meta:
        model = Number
        fields = ("number",)

from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email", "first_name", "last_name")

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

juryapp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Panel, Jury, User, Message
from .forms import *
from .text import text
from django.contrib.auth import login
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from datetime import *


@login_required
def home(request):
    first = False
    jury_list = Jury.objects.filter(judge=request.user)
    jury_form = JuryCreate()
    message_form = MessageForm()
    panels = Panel.objects.all()
    if request.method == "POST":
        if 'jury_form' in request.POST:
            form = JuryCreate(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                jury = Jury.objects.create(judge=request.user, casename=data["casename"])
                for x in range(1, (data.get('panel_num')+1)):
                    Panel.objects.create(jury=jury, number=x)
    user = User.objects.get(username=request.user)
    diff = (datetime.now(timezone.utc) - user.date_joined)
    print(diff)
    if diff.seconds < 20:
        first = True
    else:
        first = False
    return render(request, "home.html", {"jury_list": jury_list, "jury_form": jury_form, "message_form": message_form, "panels": panels, "first": first})

@login_required
def send_all(request, jury):
    if request.method == "POST":
        if 'message_form' in request.POST:
            form = MessageForm(request.POST)
            if form.is_valid():
                message = form.save(commit=False)
                message.judge = request.user
                message_jury = Jury.objects.get(pk=jury)
                message_panel = Panel.objects.filter(jury=message_jury)
                user = User.objects.get(username=request.user)
                message.save()
                for x in message_panel:
                    message.panel.add(x)
                    for member in x.members.all():
                            text(member, message, user.last_name)
                            pass
        if 'jury_form' in request.POST:
            form = JuryCreate(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                jury = Jury.objects.create(judge=request.user, casename=data["casename"])
                for x in range(1, (data.get('panel_num')+1)):
                    Panel.objects.create(jury=jury, number=x)
    jury_form = JuryCreate()
    message_form = MessageForm()
    jury_list = Jury.objects.filter(judge=request.user)
    jury = Jury.objects.get(pk=jury)
    panels = Panel.objects.filter(jury=jury)
    query = Message.objects.none()
    members = Number.objects.none()
    for panel in panels:
        query = query.union(Message.objects.filter(panel=panel)).order_by('-timestamp')
        members = members.union(panel.members.all())
    paginator = Paginator(query, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "home.html", {"jury_list": jury_list, "jury_form": jury_form, "message_form": message_form, "jury": jury, "messages": page_obj, "panels":Panel.objects.all(), "page":0, "members":members})

@login_required
def send_panel(request, jury, panel_num):
    if request.method == "POST":
        if 'message_form' in request.POST:
            form = MessageForm(request.POST)
            if form.is_valid():
                message = form.save(commit=False)
                message.judge = request.user
                message_jury = Jury.objects.get(pk=jury)
                message_panel = Panel.objects.get(jury=message_jury, number=panel_num)
                message.save()
                message.panel.add(message_panel)
                user = User.objects.get(username=request.user)
                for member in message_panel.members.all():
                         text(member, message, user.last_name)
                         pass
        if 'jury_form' in request.POST:
            form = JuryCreate(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                jury = Jury.objects.create(judge=request.user, casename=data["casename"])
                for x in range(1, (data.get('panel_num')+1)):
                    Panel.objects.create(jury=jury, number=x)
    jury_form = JuryCreate()
    message_form = MessageForm()
    jury_list = Jury.objects.filter(judge=request.user)
    jury = Jury.objects.get(pk=jury)
    panels = Panel.objects.all()
    panel = Panel.objects.get(jury=jury, number=panel_num)
    query = Message.objects.filter(panel=panel).order_by('-timestamp')
    members = panel.members.all()
    paginator = Paginator(query, 5)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    link = "https://www.court-connect.net/add/" + str(panel.id)
    return render(request, "home.html", {"jury_list": jury_list, "jury_form": jury_form, "message_form": message_form, "jury": jury, "messages": page_obj, "panels":panels, "qrcode_panel":panel, "page":int(panel_num), "members":members, "link": link})

def add_number(request, panel):
    if request.method == "POST":
        print("POST")
        form = AddJuror(request.POST)
        if form.is_valid():
            print("VALID")
            juror = form.save(commit=False)
            juror.save()
            juror_panel = Panel.objects.get(pk=panel)
            juror_panel.members.add(juror)
            number = juror.pk
            return redirect('juryapp:dash', panel, number)
    form = AddJuror()
    return render(request, "add_juror.html", {"form": form})

def dash(request, panel, number):
    dash_panel = Panel.objects.get(pk=panel)
    panel_num = dash_panel.number
    number = Number.objects.get(pk=number)
    return render(request, "dash.html", {"number": number, "panel_num": panel_num})

def qr(request, panel):
    panel = Panel.objects.get(pk=panel)
    jury = Jury.objects.get(pk=panel.jury.pk)
    panel_num = panel.number
    url = ("https://juryapp-production.up.railway.app/add/"+str(panel.pk))
    return render(request, "qrcode.html", {"link":url, "panel_num":panel_num, "jury":jury, "top_nav": True})

def register(request):
    if request.method =='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('juryapp:home'))
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def delete(request, jury):
     jury = Jury.objects.get(pk=jury)
     jury.delete()
     return redirect('juryapp:home')

def delete_number(request, member, jury):
     number = Number.objects.get(pk=member)
     number.delete()
     jury=Jury.objects.get(pk=jury)
     return redirect('juryapp:send_all', jury.pk)

def settings(request):
    user = User.objects.get(username=request.user)
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
    else:
        form = UpdateUserForm(initial={'username': user.username, 'email': user.email, 'first_name': user.first_name, 'last_name': user.last_name})
    return render(request, 'settings.html', {'form': form})

juryapp/templates/account_base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CourtConnect</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>

<body class="container d-flex min-vh-100 justify-content-center align-items-center bg-light">
    <div class="card mb-3" style="width: 30em;">
        <div class="card-body">
          <div class="d-flex justify-content-center">
          <img src="{% static 'logov2.png' %}" width="170px" class="me-2 mb-2">
        </div>
        <div class="d-flex justify-content-center">
          <div class="w-100 mx-4">
          {% block content %}

            {% endblock %}
          </div>
          </div>
        </div>
      </div>
</body>
</html>

juryapp/templates/add_juror.html
{% extends 'account_base.html' %}

{% block content %}

{% if form.errors %}
    {{ form.errors }}
{% endif %}
<div class="py-4">
<p class="text-center">Enter your phone number with no dashes to receive SMS updates from the judge for your panel and the entire jury</p>
<div class="d-flex justify-content-center">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary"
            type="submit">Submit
    </button>
</form>
</div>
</div>
{% endblock content %}

juryapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CourtConnect</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
<body class="">
  <div class="container-fluid">
    <div class="row min-vh-100" >
        <div class="col-lg-4 bg-dark">
          <div class="row">
          <div class="">
            <div class="d-flex flex-column px-3 p-3 text-bg-dark">
              <div class="d-flex justify-content-between align-items-center">
                <div class="m-0 p-0">
                <a href="{% url 'juryapp:home' %}" class="d-flex align-items-center mb-3 text-white text-decoration-none">
                  <a class="navbar-brand text-light fs-4" href="{% url 'juryapp:home' %}">CourtConnect<img src="{% static 'logov1.png' %}" width="60px" class=""></a>
                </a>
                </div>
                <div class="dropdown">
                  <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <strong>User</strong>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark text-small shadow">
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    <li><a class="dropdown-item" href="{% url 'juryapp:settings' %}">Settings</a></li>
                  </ul>
              </div>
            </div>
              <hr class="border border-white border-1 opacity-75">
              {% for object in jury_list %}
    
              <div class="accordion border-0 mb-3" id="o{{object.id}}">
                <div class="accordion-item bg-dark border-0">
                  <h2 class="accordion-header bg-dark border-0" id="heading{{object.id}}">
                    <button class="accordion-button bg-dark text-white fs-5 border-0 {% if jury != object %} collapsed {% endif %}" data-bs-toggle="collapse" data-bs-target="#collapse{{object.id}}" aria-expanded="false" aria-controls="collapse{{object.id}}">
                      <a data-bs-toggle="modal" data-bs-target="#j{{object.pk}}"><i class="bi bi-x-circle me-4 hover"></i></a>
                      {{object}}
                    </button>
                  </h2>
                  <div id="collapse{{object.id}}" class="accordion-collapse collapse {% if jury == object %} show {% endif %}" aria-labelledby="heading{{object.id}}" data-bs-parent="#o{{object.id}}">
                    <div class="accordion-body border-0">
                      
                      <ul class="nav nav-pills flex-column mb-auto border-0">
                        <li class="nav-item border-0">
                          <a href="{% url 'juryapp:send_all' object.pk %}" class="nav-link {% if page == 0 and jury == object %} active bg-blue {% else %} text-white {% endif%}" aria-current="page">
                            All Jurors
                          </a>
                        </li>
                        {% for panel in panels %}
                        {% if panel.jury == object %}
                        <li>
                          <a class="nav-link {% if page == panel.number and jury == object %} active bg-blue {% else %} text-white {% endif%}" aria-current="page" href="{% url 'juryapp:send_panel' panel.jury.pk panel.number %}">
                            Panel {{ panel.number }}
                          </a>
                        </li>
                        <!--end if panel -->
                        {% endif %}
                          {% endfor %}
                      </ul>
    
                    </div>
                  </div>
                </div>
              </div>
              
              {% endfor %}
              
              <button type="button" class="btn btn-blue fs-5 mt-3" data-bs-toggle="modal" data-bs-target="#createModal">
                Create New Jury
              </button>
    
            </div>
            </div>
            </div>
        </div>
        <div class="col-lg-8 p-4 ps-5">
          {% block content %}
        
          {% endblock content %}
        </div>
    </div>
        </div>
    </div>
    </div>
    
    {% for member in members %}
    <!--Delete Modal-->
    <div class="modal fade" id="m{{member.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Are you sure you want to delete this member from this jury?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>This action cannot be undone. This juror will not only be deleted from this panel, but also from the jury, and will have to add their number again to receive messages.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <a class="btn btn-danger" href="{% url 'juryapp:delete_number' member.pk jury.pk %}">Delete</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    
    {% for jury in jury_list %}
    <!--Delete Modal-->
    <div class="modal fade" id="j{{jury.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Are you sure you want to delete this jury?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>This action cannot be undone. All jurors and panels will be deleted. Message history will still be saved.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <a class="btn btn-danger" href="{% url 'juryapp:delete' jury.pk %}">Delete</a>
          </div>
        </div>
      </div>
    </div>
    </div>
    {% endfor %}
    
    {% for panel in panels %}
    {% if panel.jury == jury %}
    
    <div class="modal fade" id="q{{panel.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">QR Code for this Panel</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="d-flex justify-content-center">
            {% load qr_code %}
            <div>{% qr_from_text link size="s" image_format="png" error_correction="L" %}</a></div>
          </div>
            <p class="text-center">Right click to download or print image. Display around courtroom or distribute to jurors to scan!</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    
    {% endif %}
    {% endfor %}
    
    <!-- Modal -->
    <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Create New Jury</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="post">
              {% csrf_token %}
              {{ jury_form.as_p }}
              <button class="btn btn-blue"
                      type="submit">Submit
              </button>
          </form>
          </div>
        </div>
      </div>
    </div>
    
    {% if first %}
    <div class="modal fade" id="onload" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"> <!-- Add this line to your code -->
      <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Welcome to CourtConnect!</h5>
              </div>
              <div class="modal-body">
                <div class="d-flex justify-content-center pb-3">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/--PcOyRG82Y?si=2oG_av6Ab5XH7efu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
              </div>
                Since it's your first day, check out our tutorial to see how to send messages to jurors in no time!
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
          </div>
      </div>
      {% endif %}
    </div> <!-- And the relavant closing div tag -->

</body>
</html>

juryapp/templates/dash.html
{% extends 'account_base.html' %}
{% block content %}

<p class="text-center">You have been successfully added to <strong>Panel {{ panel_num }}</strong>. You will now receive SMS updates at {{ number }}. If any of this info is incorrect, please alert the judge.</strong></p>

{% endblock content %}

juryapp/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<script type="text/javascript">
  window.onload = () => {
    const myModal = new bootstrap.Modal('#onload');
    myModal.show();
  }
</script>

<div class="row w-100">
  {% if jury %}
  <div>
  <div class="row w-100">

{% if members and qrcode_panel %}
  <div class="col-4">
{% else %}
<div class="col-8">
  {% endif %}
{% if page == 0 %}
<h2>All Jurors</h2>
{% else %}
<h2>Panel {{ page }}</h2>
{% endif %}
</div>
{% if qrcode_panel %}
<div class="col-4">

<button type="button" class="float-end btn btn-blue" data-bs-toggle="modal" data-bs-target="#q{{qrcode_panel.pk}}">
  QR Code
</button>

</div>
<!--endif QR-->
{% endif %}
<div class="col-4">
{% if members %}
<div class="dropdown float-end">
<a class="btn btn-blue dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
  Members
</a>

<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
  {% for member in members %}
  <li class="text-dark px-2 py-1 bg-light">
    <div class="row">
      <div class="col-sm-9">{{ member }}</div>
      <div class="col-sm-3"><a type="button" data-bs-toggle="modal" data-bs-target="#m{{member.pk}}"><i class="bi bi-x-circle-fill"></i></a></div>
    </div>
  </li>
  {% endfor %}
</ul>
</div>
<!--endif members-->
{% endif %}
</div>
</div>
</div>
<hr class="mt-3">
{% if messages %}
{% for message in messages %}

<div class="w-100 border rounded-2 p-2 my-2 bg-light">
  <div><p class="mb-0">{{ message.message }}</p></div>
  <small class="mb-0 text-secondary">{{ message.timestamp }}</small>
</div>

{% endfor %}
{% if messages.has_previous or messages.has_next %}
<div class="container-fluid d-flex justify-content-center mt-2">
<nav aria-label="Page navigation example">
<ul class="pagination">
{% if messages.has_previous %}
<li class="page-item"><a class="page-link" href="?page={{ messages.previous_page_number }}">Previous</a></li>
{% endif %}
{% for x in messages.paginator.page_range %}
<li class="page-item"><a class="page-link" href="?page={{ x }}">{{ x }}</a></li>
{% endfor %}
{% if messages.has_next %}
<li class="page-item"><a class="page-link" href="?page={{ messages.next_page_number }}">Next</a></li>
{% endif %}
</ul>
</nav>
</div>
<!--endif messages has previous or next-->
{% endif %}   
</div>

{% else %}
<div class="h-100 d-flex justify-content-center align-items-center pt-5">
<img src="{% static 'no_messages.png' %}" width="450px" class="me-2">
</div>
<!--endif messages-->
{% endif %}
<div class="w-100 position-fixed bottom-0 row start-0 pe-3 ps-5">
<div class="col-lg-4"></div>
<div class="col-lg-8">
<form method="post">
{% csrf_token %}
<div class="w-100 border rounded-2 my-3">
{{ message_form }}
</div>
</form>
</div>
</div>

{% else %}    
<h2>Welcome back, Judge {{ request.user.last_name }}</h2>
<hr>
<div class="h-100 d-flex justify-content-center align-items-center pt-5">
<img src="{% static 'logo-gray3.png' %}" width="450px" class="me-2">
</div>
</div>
<!--endif jury-->
{% endif %}

{% endblock content %}

juryapp/templates/settings.html
{% extends 'base.html' %}

{% block content %}

{% load widget_tweaks %}
<div class="d-flex justify-content-between m-0 p-0">
<h2 class="pb-2 m-0">Settings: Judge {{ request.user.first_name }} {{ request.user.last_name }}</h2>
<a href="{% url 'juryapp:home' %}"><i class="bi bi-arrow-return-left enlarge text-dark"></i></a>
</div>
<hr class="">
<div class="container">
    <form class="py-3 w-100" method="post">
        {% csrf_token %}
        <label class="form-label">Username</label>
        {{ form.username|add_class:'form-control' }}
        <label class="form-label pt-2">Email Address</label>
        {{ form.email|add_class:'form-control' }}
        <label class="form-label pt-2">First Name</label>
        {{ form.first_name|add_class:'form-control' }}
        <label class="form-label pt-2">Last Name</label>
        {{ form.last_name|add_class:'form-control' }}
        <button class="btn btn-blue mt-3" type="submit">Save</button>
    </form>
</div>

{% endblock content %}